apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: api-gw
    spec:
      containers:
      - name: otto-api-gw
        image: ghcr.io/danielmunro/otto-api-gw:v0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
            targetPort: 3000
            name: api-gw
        env:
          - name: API_ENDPOINT
            value: localhost
          - name: TARGET_COMMUNITY_SERVICE
            value: "community-service:8081"
          - name: TARGET_USER_SERVICE
            value: "user-service:8080"
          - name: TARGET_IMAGE_SERVICE
            value: "image-service:8082"
          - name: TARGET_UI
            value: "ui:3000"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: dockerconfigjson-github-com
