apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: api-gw
    spec:
      containers:
      - name: otto-api-gw
        image: ghcr.io/danielmunro/otto-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: api-gw
        env:
          - name: API_ENDPOINT
            value: localhost
#          - name: TARGET_COMMUNITY_SERVICE
#              value: "$(COMMUNITY_SERVICE_HOST):8081"
#          - name: TARGET_USER_SERVICE
#            value: "$(USER_SERVICE_SERVICE_HOST):8080"
#          - name: TARGET_IMAGE_SERVICE
#            value: "$(IMAGE_SERVICE_HOST):8082"
          - name: TARGET_UI
            value: "ui:3000"
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: dockerconfigjson-github-com
