apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: api-gw
      port:
        number: 8000
  rules:
    - host: otto.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api-gw
                port:
                  number: 8000
  containers:
    image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0"
    name: web-ingress
    ports:
      - containerPort: 80
        hostPort: 80
        name: http
        protocol: TCP
