apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gw-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: thirdplaceapp.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api-gw
                port:
                  number: 8000
