apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gw-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: thirdplaceapp.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api-gw
                port:
                  number: 8000
