apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-gw
  namespace: public-api
  description: API gateway for otto backend
  tags:
    - javascript
    - express
  links:
    - url: https://github.com/danielmunro/otto-api-gw
      title: Git Repository
spec:
  type: service
  lifecycle: production
  owner: dev-team
  consumesApis:
    - user-service
    - community-service
    - image-service
